name: train-env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - python=3.9
  - pip
  - pip:
      - --extra-index-url  https://download.pytorch.org/whl/xpu
      - torch
      - mlflow
      - torch==2.7.1+xpu
      - torchvision
